version: "3"
services:

  otel-collector:
    image: datadog-opentelemetry-collector-exporter
    depends_on: 
      - aspcore-service-a
      - aspcore-service-b

  aspcore-service-a:
    image: aspcore-service-a
    ports:
      - "5001:5001"

  aspcore-service-b:
    image: aspcore-service-b
    ports:
      - "6001:6001"
