version: "3"
services:

  otel-collector:
    image: datadog-opentelemetry-collector-exporter
    environment:
      DD_API_KEY: API_KEY_HERE
    depends_on: 
      - aspcore-service-a
      - aspcore-service-b

  aspcore-service-a:
    image: aspcore-service-a
    ports:
      - "443:443"

  aspcore-service-b:
    image: aspcore-service-b
    ports:
      - "6001:6001"
