receivers:
  otlp:
    protocols:
      http: 

exporters:
  datadog:
    env: otel # Optional 
    version: 1.0 # Optional 
    tags: ["otel:true"] # Optional 
    api:
      key: _DD_API_KEY_HERE_

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      exporters: [datadog]

